---
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: connect-input
        input-formatted:
          destination: input-records
      kafka:
        streams:
          binder:
            configuration:
              application:
                id: APP-1
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            input:
              consumer:
                auto-offset-reset: earliest
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde:  org.apache.kafka.common.serialization.Serdes$StringSerde
            input-formatted:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.abnamro.challenge.futuretxn.kafka.serde.TradeCaptureMessageSerde
        binder:
          brokers: localhost:9092


